name: ublue-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 40

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://raw.githubusercontent.com/IverCoder/ublue-os/main/repos/shiftkey-packages.repo
    install:
      - freerdp
      - github-desktop
      - gnome-console
      - powertop
      - tuned
      - tuned-gtk
      - tuned-ppd
      - tuned-profiles-atomic
      - tuned-profiles-cpu-partitioning
      - tuned-utils
      - virt-manager
      - waydroid
    remove:
      - firefox
      - firefox-langpacks
      - gnome-terminal
      - gnome-terminal-nautilus
      - power-profiles-daemon

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub"
      install:
        - io.bassi.Amberol # Amberol
        - com.raggesilver.BlackBox # Black Box
        - com.usebottles.bottles # Bottles
        - org.gnome.Calculator # Calculator
        - org.gnome.Calendar # Calendar
        - org.gnome.Snapshot # Camera
        - io.github.celluloid_player.Celluloid # Celluloid
        - org.gnome.Characters # Characters
        - org.gnome.clocks # Clocks
        - com.mattjakeman.ExtensionManager # Extension Manager
        - org.mozilla.firefox # Firefox
        - com.github.tchx84.Flatseal # Flatseal
        - com.github.GradienceTeam.Gradience # Gradience
        - org.gnome.Loupe # Image Viewer
        - org.gnome.World.Iotas # Iotas
        - org.gnome.Logs # Logs
        - io.missioncenter.MissionCenter # Mission Center
        - it.mijorus.smile # Smile
        - org.gnome.NautilusPreviewer # Sushi
        - org.gnome.TextEditor # Text Editor
        - io.github.flattool.Warehouse # Warehouse
  
  - type: script
    scripts:
      - systemd-homed-selinux.sh

  - type: systemd
    system:
      enabled:
        - tuned.service
        - systemd-homed

  - type: signing
