name: bluebuild
on:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Publish ISO
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
       # the build is fully handled by the reusable github action
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          arch: x86_64
          flatpak_remote_name: flathub
          flatpak_remote_refs: io.bassi.Amberol com.raggesilver.BlackBox com.usebottles.bottles org.gnome.Calculator org.gnome.Calendar org.gnome.Snapshot io.github.celluloid_player.Celluloid org.gnome.Characters org.gnome.clocks com.mattjakeman.ExtensionManager org.mozilla.firefox com.github.tchx84.Flatseal com.github.GradienceTeam.Gradience org.gnome.Loupe org.gnome.World.Iotas org.gnome.Logs io.missioncenter.MissionCenter it.mijorus.smile org.gnome.NautilusPreviewer org.gnome.TextEditor io.github.flattool.Warehouse
          flatpak_remote_url: https://dl.flathub.org/repo/flathub.flatpakrepo
          image_name: ublue-os
          image_repo: ghcr.io/ivercoder
          image_tag: latest
          version: 40
          variant: Silverblue
          iso_name: ${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}-${{ env.VERSION }}.iso
          web_ui: true
      - name: Upload ISO as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.iso_name }}
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}-CHECKSUM
